name: Github Actions FGC
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]    
    
jobs:
  build:
    name: ğŸ”¨ Build da aplicaÃ§Ã£o
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do cÃ³digo
      uses: actions/checkout@v4

    - name: Instalar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: ğŸ”§ Restaurar e compilar soluÃ§Ã£o
      run: dotnet build src/FGC.Api/FGC.Api.sln  --configuration Release
      
  test:
    name: âœ… Testes UnitÃ¡rios
    runs-on: ubuntu-latest
    needs: build  # depende do job de build

    steps:
    - name:  Checkout do cÃ³digo
      uses: actions/checkout@v4

    - name: Instalar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Executar testes
      run: |
        dotnet test src/FGC.UnitTests/FGC.UnitTests.csproj --configuration Debug --verbosity normal
        dotnet test src/FGC.BDD/FGC.BDD.csproj --configuration Debug --verbosity normal

  push:
    name: ğŸš€ Docker Build & Push
    runs-on: ubuntu-latest
    needs: test  # depende do job de test

    steps:
    - name: ğŸ“¥ Checkout do cÃ³digo
      uses: actions/checkout@v4

    - name: ğŸ” Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: ğŸ³ Build e Push da imagem Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: vitordietrich/fiap-api:latest
